ALTER TABLE accounts ADD COLUMN IF NOT EXISTS bank_name TEXT;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS account_number TEXT;
ALTER TABLE cards ADD COLUMN IF NOT EXISTS bank_name TEXT;
ALTER TABLE cards ADD COLUMN IF NOT EXISTS last4 TEXT;
